razee-io/razeedeploy-core

lib/BaseDownloadController.js
promise.all should finish applying all child resources from a downloaded file before rejecting out. use optional flag to allow further files to be downloaded and applied from the requests list
=> allow promise.all to finish

lib/BaseController.js
we use last applied to reconcile future applies (to know what the user added to be able to delete when the user deletes from the file). So the last applied should be added on the post, and warning only if the resource already exists on the system but last-applied not found.
=> add last applied on file post

lib/BaseDownloadController.js
just remove if modified since from the request and move on. This seems to be causing odd behavior, where the versions keep flipping back and forth in the url when we update the whole array. some transient modfied event comes through and switches it back, while the new one is trying to flip it forward. bad juju.
=> Dont update original request array

lib/BaseDownloadController.js, lib/CompositeController.js
If an error from kube comes back when applying a child and doesn't have a status code, this child will get deleted. This fixes that by defining a response with no status codde as an error.
=> Catch kube errors when no status code returned

.travis.yml, lib/FetchEnvs.js, package-lock.json, package.json
When trying to copy a multiline json string from a yaml to a string in another yaml, there are issues with the JSON being parsed during the initial get which is undesireable. if this edge case applies to you, you can use this new type jsonString to let us know it is a json string that you want to stay a json string at its destination. we will force the quotes back to the proper escape level.
=> Fix: edge case for transplanting multiline json string

lib/BaseController.js, package-lock.json
reconcilefileds should only set field to null when lastapplied path exists and new path is undefined.
=> Fix: reconcile incorrectly nulls falsey values

lib/FetchEnvs.js, package-lock.json
Dont remove all whitespaces from the json string. Switching to using json.stringify so we dont have to worry about processing the json correctly. Still have to remove the quotes stringify adds to account for having to put quotes around our template curly braces.
=> Fix: whitespace removed from jsonString

lib/BaseController.js, lib/BaseDownloadController.js, lib/CompositeController.js
this is the first step in better authentication around razee resources. this feature allows razeedeploy resources to impersonate a user that is specified in the spec.
In the future we will need much better guard rails to prevent users from impersonating others, but for now its not much different then them just allowing razeedeploy do it.
=> feat: allow razeedeploy to impersonate user

lib/BaseController.js, lib/BaseTemplateController.js
this bug was found when a user had a MTP create a resource with an annotation section defined. They then updated their mtp and no longer defined the annotation section. This caused the reconcileFields function to null the entire annotations section. We then tell objectPath to null out the old kapitan/last-applied annotation, and it promply fails because it cant set a value to a null field.
Not only will the commit fix that user issue, it will also prevent us destroying other items in a resource that a user may stop defining but may not what the whole thing deleted (like some default set by kube or a third party)
=> fix: dont null whole objects if a resource stops creating it

lib/BaseController.js
dont try to null object child values if the parent is already set to null.
{test:{ values: 123}}
=>
{test: null}
we will avoid trying to set values to null because test is already null
=> fix: cant set null if user already set value to null

lib/BaseController.js
The current common model in k8s of providing a last-applied-configuration gave me an idea for addressing #156.  Basically, instead of trying to find some way to expose the configuration via an API or the logs, put it on the resources now.  
Yes, the con here is that you are editing the resource, but only a piece of metadata.
Anyone could write a wrapper to extract this and compare to the existing to identify what is going to change.
This does not address the following:
* How cluster locking works.  because it would be really good to also have this information for when a cluster is locked, cause the scope of change is much larger.
* If you are doing nested dependencies, such as locking a configmap that affects a mustache template, then only the configmap would get this annotation.  Not …
=> Add metadata showing upcoming changes on debug'd resources

.eslintrc.json, .travis.yml, lib/BaseController.js, lib/FetchEnvs.js, package-lock.json, package.json
Allow `matchLabels` on key ref lookups. This is primarily to enable
config map discovery when merging JSON keys. Allowing lable selectors
means a single mtp doesn't have to add a key lookup for every configmap
it wishes to source from.
fixes: razee-io/MustacheTemplate#296
=> feat(fetchenv): allow label selectors on key lookups

lib/FetchEnvs.js, package-lock.json, test/fetchEnvs-tests.js
path can be any length, that may or may not exist. so need a way to fetch env/envFrom given the user's defined path.
=> fix: allow fetchenvs to traverse multi-level env paths

lib/BaseController.js, lib/CompositeController.js
allow user to define label `deploy.razee.io/mode: AdditiveMergePatch` on a child resource to avoid razeedeploy setting the `last-applied-configuration` annotation on said child resource.
Removes support of old `kapitan` naming for label/annotations.
=> feat[Breaking]: Additive merge patch

lib/BaseController.js, lib/BaseDownloadController.js, lib/BaseTemplateController.js, lib/CompositeController.js
Related to this issue: https://github.com/razee-io/razeedeploy-core/issues/189
Admission webhook was created [HERE](https://github.com/razee-io/ImpersonationWebhook) to validate if an authenticated user has impersonation permission. The restriction in the base controllers should be removed since the webhook already handles validation. This means that razee controllers and the webhook must be deployed together.
**Potential breaking changes:**
- Currently, anyone can impersonate others when creating resources in `razeedeploy` namespace. With this change, this will not be allowed if authenticated users are not granted impersonate permission, and the `impersonateUser` field will be set to the authenticated user by the webhook.
- Currently, `impersonateUser` field is set to `razeedeploy` by …
=> remove impersonation restriction

index.js, lib/BaseTemplateController.js, lib/MockController.js, lib/MockKubeResourceMeta.js, test/fetchEnvs-tests.js
- these will enable simpler testing here
- it should also enable simpler testing of the `mustachetemplate`
controller
- this is also ground work for a PR to `mustachetemplate` to add a new
script it its `bin/` that can render MTPs from files on disk, instead
of only k8s resources in a live environment, to enable better testing
of MTPs generally
=> feat: add `MockController`, `MockKubeResourceMeta`

lib/BaseController.js, test/basecontroller-tests.js
Base controller accepts a `reconcileByDefault` option which controls the default value for the reconciler behavior when `deploy.razee.io/Reconcile` is not specified. By default it is true.
It must be a boolean looking value. 1, or 0 are not valid
=> feat(base): allow default reconcile behavior to be configured

lib/BaseDownloadController.js
Bugfix: prevent processing that never completes when resources to be applied contains five or more Lists.
Bug originally introduced in https://github.com/razee-io/razeedeploy-core/pull/344
=> do not limit recursion into lists

lib/BaseController.js, lib/CompositeController.js
https://github.com/razee-io/RemoteResource/issues/399
This PR addresses a gap from https://github.com/razee-io/razeedeploy-core/pull/360, where `Reconcile: false` children left on a cluster after parent RR deletion (orphans) would keep a reference to their prior parent and could not be modified by future RemoteResources.
=> Ensure parent cleanup and ability to become parent of an orphan

lib/FetchEnvs.js, lib/ReferencedResourceManager.js, package-lock.json, test/fetchEnvs-test-scenarios/env_scenarios.json
Optimized resource retrieval for FetchEnvs, using a cache to ensure resources are not retrieved from kube multiple times.
- Cache is keyed per user to prevent incorrect access.
- Cache has a 3 minute TTL to ensure resources are not served from cache for long periods.
- Cache can be selectively cleared, e.g. when RRM receives an event for a modified/deleted resource, the RRM removes the resource from the cache before processing further.
Ref: https://github.com/razee-io/MustacheTemplate/issues/463
=> Optimized resource retrieval for FetchEnvs

lib/FetchEnvs.js
- Ensure cached objects are cloned first, so that cache is not accidentally altered by modifications to retrieved objects (fixed bug introduced in razeedeploy-core 1.3.5 and included in 1.3.6)
- Increase default FetchEnvs cache size.
=> Ensure cached objects are cloned first

lib/CompositeController.js
- Improved log statements and variable naming
- Bug-fix in `_patchChild` to prevent exception if the child to be patched has already been deleted (could happen with user action) or is not updatable (should not happen).
=> Avoid errors removing parent ref from deleted resources
